### ISSUE TITLE
Reverted Commit because it did not build

### ISSUE THREAD

**Issue by v1kko** [GEMDAT-repos/gemdat-notebooks#5]
@SCiarella I reverted commit https://github.com/GEMDAT-repos/gemdat-notebooks/commit/10a0d0f22197ca3611bc897b03dc7174bc779bba which has an error while building (also on read the docs):

See error at https://readthedocs.org/projects/gemdat/builds/23121060/ or below:
```
ERROR   -  Error reading page 'notebooks/paths.ipynb': Expecting value: line
           277722 column 3 (char 5385088)
Traceback (most recent call last):
  File "/home/vikko/local_projects/GEMDAT/.venv/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/home/vikko/local_projects/GEMDAT/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vikko/local_projects/GEMDAT/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/vikko/local_projects/GEMDAT/.venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vikko/local_projects/GEMDAT/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vikko/local_projects/GEMDAT/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vikko/local_projects/GEMDAT/.venv/lib/python3.11/site-packages/mkdocs/__main__.py", line 270, in serve_command
    serve.serve(**kwargs)
  File "/home/vikko/local_projects/GEMDAT/.venv/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 86, in serve
    builder(config)
  File "/home/vikko/local_projects/GEMDAT/.venv/lib/python3.11/site-packages/mkdocs/commands/serve.py", line 67, in builder
    build(config, live_server=None if is_clean else server, dirty=is_dirty)
  File "/home/vikko/local_projects/GEMDAT/.venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 322, in build
    _populate_page(file.page, config, files, dirty)
  File "/home/vikko/local_projects/GEMDAT/.venv/lib/python3.11/site-packages/mkdocs/commands/build.py", line 175, in _populate_page
    page.render(config, files)
  File "/home/vikko/local_projects/GEMDAT/.venv/lib/python3.11/site-packages/mkdocs_jupyter/plugin.py", line 107, in new_render
    body = convert.nb2html(
           ^^^^^^^^^^^^^^^^
  File "/home/vikko/local_projects/GEMDAT/.venv/lib/python3.11/site-packages/mkdocs_jupyter/nbconvert2.py", line 145, in nb2html
    nb_json = json.load(f)
              ^^^^^^^^^^^^
  File "/nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/lib/python3.11/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/ffll6glz3gwx342z0ch8wx30p5cnqz1z-python3-3.11.5/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 277722 column 3 (char 5385088)
```

**Comment by SCiarella** [comment]
Sorry, I have updated the path.ipynb to work with the label-landscape-sites branch. I will update the notebook when #213 is closed. Thanks
